Fix elk 7 {conf,env}.d sample
Neither elastic nor logstash elements were present in container_skel
while they were referenced in component_skel which is not valid for
dynamic_inventory. So attempt to generate it resulted in:
KeyError: 'elastic-logstash' here [1]

Also elaborate more on conf.env sample as per the intents of
https://review.opendev.org/c/openstack/openstack-ansible-ops/+/707849

[1] https://opendev.org/openstack/openstack-ansible/src/branch/master/osa_toolkit/generate.py#L266

Change-Id: I74a4788ff25c5ef45c064d1f8309002b1731ad7a